# Generated by Django 6.0.3 on 2026-03-27 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractor_name', models.CharField(max_length=200)),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to='bids/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='projects.project')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='BidItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=500)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bid_items', to='bids.bid')),
            ],
        ),
        migrations.CreateModel(
            name='RiskAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overprice_items', models.JSONField(default=list)),
                ('underprice_items', models.JSONField(default=list)),
                ('missing_items', models.JSONField(default=list)),
                ('risk_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('bid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='riskanalysis', to='bids.bid')),
            ],
        ),
    ]
