# Generated by Django 6.0.3 on 2026-03-28 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='organizationmember',
            options={'ordering': ['-joined_at']},
        ),
    ]
