# Generated by Django 6.0.3 on 2026-03-28 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_alter_organization_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={},
        ),
        migrations.AlterModelOptions(
            name='organizationmember',
            options={},
        ),
    ]
